scan_timeout = 50
command_timeout = 1000
add_newline = false

[character]
success_symbol = "â˜‘ï¸  "
error_symbol = "ğŸš« "

[aws]
disabled = true

[cmake]
format="[$symbol($version )]($style)"
version_format="${major}.${minor}"
symbol="CMake "
style="blue"
disabled=false

[conda]
ignore_base = false
format = "[$symbol$environment](green) "

[git_branch]
format="[$symbol$branch(:$remote_branch)]($style) "
symbol = "ğŸ”€ "
truncation_length = 10
truncation_symbol = "â€¦"
style = "yellow"

[git_commit]
commit_hash_length = 8
tag_symbol = "ğŸ”– "
only_detached = false
tag_disabled = false
style = "yellow"

# https://gitmoji.dev/
[git_status]
style = "grey"
conflicted = "ğŸ³"
ahead = "ğŸ"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ…"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[memory_usage]
disabled = false
threshold = -1
symbol = "ğŸ§ "
style = "bold dimmed grey"
format = "$symbol [${ram}]($style) "

[singularity]
format = '[ğŸ“¦ \[$env\]]($style) '

[time]
disabled = false
style = "dimmed grey"
format = 'â° [$time]($style) '
time_format = "%T"

[username]
style_user = "white bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[spack]
format = '[$symbol$environment](dimmed blue) '

