scan_timeout = 50
command_timeout = 1000
add_newline = false

[character]
success_symbol = "[â†³](bold blue)"
error_symbol = "[âœ—](bold red)"

[aws]
disabled = true

[conda]
ignore_base = false
format = "[$symbol$environment](green) "

[git_branch]
symbol = "ğŸ”€ "
truncation_length = 4
truncation_symbol = "â€¦"

[git_commit]
commit_hash_length = 7
tag_symbol = "ğŸ”– "
only_detached = false
tag_disabled = false
style = "yellow"

# https://gitmoji.dev/
[git_status]
style = "grey"
conflicted = "ğŸ³"
ahead = "ğŸ"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ…"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[memory_usage]
disabled = false
threshold = -1
symbol = "ğŸ§ "
style = "bold dimmed grey"
format = "$symbol [${ram}]($style) "

[singularity]
format = '[ğŸ“¦ \[$env\]]($style) '

[time]
disabled = false
style = "dimmed grey"
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"


[username]
style_user = "white bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true